settings:
  beVerbose: true
  AllowBase: true
  AllowNoRace: false
races:
  pegasus:
    hasBase: true
    isOpen: true
    baseX: 221.0
    baseY: 70.0
    baseZ: 340.0
    yaw: 0.0
    pitch: 0.0
    permissions:
      permissions.build: true
      races.fly: true
    players:
    - Sanchezator
  unicorn:
    hasBase: true
    isOpen: true
    baseX: 0.0
    baseY: 0.0
    baseZ: 0.0
    yaw: 0.0
    pitch: 0.0
    permissions:
      permissions.build: true
    players: []